### ISSUE TITLE
Game Keeps Crashing

### ISSUE THREAD

**Issue by Emysry** [McJty/InControl#10]
I'm having some trouble getting this mod work properly. I'm on Minecraft 1.10.2, and whenever I try to allow/deny certain mobs spawning, my game will crash when I try to start it up.

 I was working with the spawn.json, trying a few different things, and it would always crash. I wasn't sure what the problem was, so I deleted everything I had typed myself, and copy/pasted in one of the examples from the InControl wiki just to see if the mod was working properly.
 
[
  {
    "mob": ["Creeper", "Skeleton"],
    "result": "allow"
  },
  {
    "passive": true,
    "result": "allow"
  },
  {
    "result": "deny"
  }
]

It caused my game to crash as well. Here's the crash report I keep getting:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 3/26/17 1:01 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from InControl (incontrol)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/util/datafix/fixes/EntityId
	at mcjty.lib.tools.EntityTools.<clinit>(EntityTools.java:27)
	at mcjty.incontrol.rules.support.GenericRuleEvaluator.addMobsCheck(GenericRuleEvaluator.java:249)
	at mcjty.incontrol.rules.support.GenericRuleEvaluator.addChecks(GenericRuleEvaluator.java:98)
	at mcjty.incontrol.rules.support.GenericRuleEvaluator.<init>(GenericRuleEvaluator.java:37)
	at mcjty.incontrol.rules.SpawnRule.<init>(SpawnRule.java:130)
	at mcjty.incontrol.rules.SpawnRule.parse(SpawnRule.java:394)
	at mcjty.incontrol.rules.RulesManager$$Lambda$8/1212425443.apply(Unknown Source)
	at mcjty.incontrol.rules.RulesManager.readRules(RulesManager.java:92)
	at mcjty.incontrol.rules.RulesManager.readAllRules(RulesManager.java:79)
	at mcjty.incontrol.rules.RulesManager.readRules(RulesManager.java:33)
	at mcjty.incontrol.proxy.CommonProxy.postInit(CommonProxy.java:29)
	at mcjty.incontrol.InControl.postInit(InControl.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:800)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.datafix.fixes.EntityId
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 50 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 160057272 bytes (152 MB) / 511115264 bytes (487 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJ	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJ	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJ	customnpcs{1.9.0_beta} [CustomNPCs] (CustomNPCs_1.10.2_beta(10oct16).jar) 
	UCHIE	incontrol{3.5.4} [InControl] (incontrol-3.5.4 (1).jar) 
	UCHIJ	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCHIJ	MCA{1.10.2-5.2.2} [Minecraft Comes Alive] (MCA-1.10.2-5.2.2-universal.jar) 
	UCHIJ	worldedit{6.1.6} [WorldEdit] (worldedit-forge-mc1.11-6.1.6-dist.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.54' Renderer: 'GeForce GT 720/PCIe/SSE2'

I'm not super experienced when it comes to mods, so whatever I'm doing wrong might be really simple/obvious.

Note:
I'm not sure if this is related to the problem at all, but I have a few other mods installed as well. They are:
-Custom NPCs
-World Edit
-MCA

My end goal is to only let mobs from Custom NPCs and MCA spawn, and none of the vanilla mobs. I feel like this should be pretty simple to do once I get the mod to stop crashing.

Thanks!

**Comment by Emysry** [comment]
Update:
I didn't realize that there was a rule I could use to allow/deny an entire mod, so I actually was able to get it to do what I wanted by entering:
[
  {
     "mod": "customnpcs",
     "result": "allow"
  },
  {
     "result": "deny"
  }
]

That worked just fine! I'm completely happy now, so this ticket isn't urgent anymore. However, the original problem I had still persists, so it would be good to know what I was doing wrong anyway. Just in case I ever need to use that function in the future.

**Comment by McJty** [comment]
hmm this is weird. What CompatLayer are you using?

**Comment by Emysry** [comment]
Ooooh, yep. It looks like I grabbed the 1.11 version by mistake.

I checked to make sure that I had the right version of InControl, but I had completely forgot about CompatLayer.
Switching to the 1.10 version seem to have resolved all my issues. I knew my problem would be something really obvious like that. 

Thanks so much!
