### ISSUE TITLE
Ice and Fire 1.8.0 version has varied mobs that seem to ignore deny rule

### ISSUE THREAD

**Issue by Asstuba** [McJty/InControl#147]
I am guessing the way Ice and Fire has been re-written for the varied mob model for cyclops is causing InControl to fail my deny rule, I was going to report this to the Ice and Fire author, but I thought that there was potential for another mod to spawn mobs with texture variations in this way.

This is the change I suspect:
https://github.com/Alex-the-666/Ice_and_Fire/commit/d148626de4163347eff74a17e119f0b9b215b417#diff-876c5286a83fa60015c28ef89cd6fc2d

Successful spawn control deny condition:

InControl 1.2-3.9.15
Ice and Fire 1.7.1-1.12.2

Spawns cyclopes indefinitely, seems to ignore the deny rule condition:

InControl 1.2-3.9.15
Ice and Fire 1.8.0-1.12.2

potentialspawn.json:
```
[
    {
      "dimension": 0,
      "mobs": [
        {
          "mob": "iceandfire:cyclops",
          "weight": 5,
          "groupcountmin": 1,
          "groupcountmax": 2
        }
      ]
    }
  ]
```
spawn.json:
```
[
    {
        "dimension": 0,
        "mob": [
            "iceandfire:cyclops"
        ],
        "biome": [
            "Plains"
        ],
        "maxcount": {
            "perchunk": true,
            "amount": 3
        },
        "block": "minecraft:grass",
        "seesky": true,
        "isnotcolliding": true,
        "result": "allow"
    },
    {
        "dimension": 0,
        "mob": [
            "iceandfire:cyclops"
        ],
        "result": "deny"
    }
]
```

**Comment by McJty** [comment]
Hmm not sure. But what happens if you try to add "onjoin": true to the deny rule?

**Comment by Asstuba** [comment]
"onjoin": true in the deny rule seems to catch them, but then none spawn at all.

**Comment by McJty** [comment]
Well in that case you also have to add the "onjoin": true to the allow rule so that that rule works as well

**Comment by Asstuba** [comment]
That results in the following crash:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 8/16/19 5:11 AM
Description: Exception in world tick

java.lang.ClassCastException: net.minecraft.client.multiplayer.WorldClient cannot be cast to net.minecraft.world.WorldServer
	at mcjty.incontrol.rules.RuleCache$CachePerWorld.getValidSpawnChunks(RuleCache.java:124)
	at mcjty.incontrol.rules.RuleCache.getValidSpawnChunks(RuleCache.java:33)
	at mcjty.incontrol.rules.support.GenericRuleEvaluator.lambda$getAmountAdjuster$16(GenericRuleEvaluator.java:441)
	at mcjty.incontrol.rules.support.GenericRuleEvaluator$$Lambda$216/1216999539.apply(Unknown Source)
	at mcjty.incontrol.rules.support.GenericRuleEvaluator.lambda$addMaxCountCheck$15(GenericRuleEvaluator.java:433)
	at mcjty.incontrol.rules.support.GenericRuleEvaluator$$Lambda$217/1187114910.apply(Unknown Source)
	at mcjty.incontrol.rules.support.GenericRuleEvaluator.match(GenericRuleEvaluator.java:594)
	at mcjty.incontrol.rules.SpawnRule.match(SpawnRule.java:254)
	at mcjty.incontrol.ForgeEventHandlers.onEntityJoinWorld(ForgeEventHandlers.java:37)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_67_ForgeEventHandlers_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1206)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:196)
	at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:97)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1870)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mcjty.incontrol.rules.RuleCache$CachePerWorld.getValidSpawnChunks(RuleCache.java:124)
	at mcjty.incontrol.rules.RuleCache.getValidSpawnChunks(RuleCache.java:33)
	at mcjty.incontrol.rules.support.GenericRuleEvaluator.lambda$getAmountAdjuster$16(GenericRuleEvaluator.java:441)
	at mcjty.incontrol.rules.support.GenericRuleEvaluator$$Lambda$216/1216999539.apply(Unknown Source)
	at mcjty.incontrol.rules.support.GenericRuleEvaluator.lambda$addMaxCountCheck$15(GenericRuleEvaluator.java:433)
	at mcjty.incontrol.rules.support.GenericRuleEvaluator$$Lambda$217/1187114910.apply(Unknown Source)
	at mcjty.incontrol.rules.support.GenericRuleEvaluator.match(GenericRuleEvaluator.java:594)
	at mcjty.incontrol.rules.SpawnRule.match(SpawnRule.java:254)
	at mcjty.incontrol.ForgeEventHandlers.onEntityJoinWorld(ForgeEventHandlers.java:37)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_67_ForgeEventHandlers_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1206)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:196)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Asstuba'/100, l='MpServer', x=-470.72, y=72.49, z=250.73]]
	Chunk stats: MultiplayerChunkCache: 1089, 1089
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-112,64,240), Chunk: (at 0,4,0 in -7,15; contains blocks -112,0,240 to -97,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 28497 game time, 15124 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 99 total; [EntityBat['Bat'/518, l='MpServer', x=-472.25, y=27.10, z=172.48], EntitySheep['Sheep'/285, l='MpServer', x=-542.62, y=67.00, z=201.54], EntitySheep['Sheep'/286, l='MpServer', x=-543.61, y=67.00, z=204.47], EntityBat['Bat'/542, l='MpServer', x=-444.56, y=40.39, z=322.21], EntitySheep['Sheep'/287, l='MpServer', x=-543.59, y=67.00, z=201.65], EntityCreeper['Creeper'/289, l='MpServer', x=-535.50, y=68.00, z=188.50], EntitySkeleton['Skeleton'/290, l='MpServer', x=-499.50, y=54.00, z=188.50], EntityBat['Bat'/291, l='MpServer', x=-503.42, y=54.12, z=195.42], EntityBat['Bat'/292, l='MpServer', x=-514.34, y=24.03, z=185.13], EntityZombie['Zombie'/293, l='MpServer', x=-526.54, y=22.00, z=218.75], EntityBat['Bat'/294, l='MpServer', x=-488.49, y=43.93, z=168.61], EntitySkeleton['Skeleton'/295, l='MpServer', x=-486.50, y=64.00, z=180.50], EntitySkeleton['Skeleton'/296, l='MpServer', x=-498.50, y=35.00, z=195.50], EntitySheep['Sheep'/299, l='MpServer', x=-488.28, y=63.00, z=195.51], EntitySheep['Sheep'/300, l='MpServer', x=-486.30, y=63.00, z=194.44], EntityBat['Bat'/301, l='MpServer', x=-511.44, y=45.31, z=205.20], EntityPig['Pig'/302, l='MpServer', x=-513.71, y=73.00, z=237.54], EntitySpider['Spider'/305, l='MpServer', x=-489.50, y=66.00, z=210.50], EntitySheep['Sheep'/308, l='MpServer', x=-498.49, y=69.00, z=239.70], EntityPig['Pig'/309, l='MpServer', x=-519.47, y=70.00, z=254.72], EntityPig['Pig'/310, l='MpServer', x=-508.74, y=71.00, z=248.25], EntityPig['Pig'/311, l='MpServer', x=-513.49, y=72.00, z=260.25], EntitySheep['Sheep'/314, l='MpServer', x=-493.95, y=69.00, z=239.52], EntitySheep['Sheep'/315, l='MpServer', x=-488.55, y=67.16, z=241.46], EntitySheep['Sheep'/316, l='MpServer', x=-497.27, y=68.00, z=236.49], EntitySheep['Sheep'/317, l='MpServer', x=-524.51, y=67.06, z=280.97], EntitySkeleton['Skeleton'/321, l='MpServer', x=-542.50, y=69.00, z=263.50], EntityZombie['Zombie'/336, l='MpServer', x=-453.27, y=71.00, z=230.69], EntitySheep['Sheep'/341, l='MpServer', x=-469.33, y=69.00, z=258.73], EntitySheep['Sheep'/342, l='MpServer', x=-466.53, y=69.00, z=257.26], EntityZombie['Zombie'/345, l='MpServer', x=-481.79, y=65.00, z=288.53], EntityCreeper['Creeper'/346, l='MpServer', x=-463.80, y=66.00, z=281.60], EntityZombie['Zombie'/347, l='MpServer', x=-437.74, y=59.00, z=252.53], EntityPig['Pig'/350, l='MpServer', x=-433.30, y=71.00, z=247.23], EntitySheep['Sheep'/351, l='MpServer', x=-433.36, y=71.00, z=243.72], EntityPig['Pig'/352, l='MpServer', x=-504.80, y=72.00, z=305.76], EntityPig['Pig'/353, l='MpServer', x=-511.50, y=74.00, z=311.50], EntityPig['Pig'/354, l='MpServer', x=-503.74, y=71.00, z=312.48], EntitySpider['Spider'/103, l='MpServer', x=-475.00, y=68.00, z=227.00], EntitySheep['Sheep'/104, l='MpServer', x=-481.17, y=69.00, z=242.15], EntitySheep['Sheep'/361, l='MpServer', x=-462.68, y=66.00, z=280.44], EntitySheep['Sheep'/362, l='MpServer', x=-462.50, y=66.00, z=283.79], EntitySheep['Sheep'/363, l='MpServer', x=-460.16, y=66.00, z=281.21], EntitySheep['Sheep'/364, l='MpServer', x=-460.72, y=66.00, z=282.22], EntityCreeper['Creeper'/365, l='MpServer', x=-438.82, y=59.00, z=260.22], EntitySpider['Spider'/366, l='MpServer', x=-443.30, y=61.00, z=261.70], EntityPig['Pig'/367, l='MpServer', x=-435.47, y=65.00, z=276.75], EntitySpider['Spider'/379, l='MpServer', x=-437.50, y=38.00, z=308.50], EntityCreeper['Creeper'/380, l='MpServer', x=-441.50, y=64.00, z=315.50], EntityZombie['Zombie'/390, l='MpServer', x=-456.50, y=42.00, z=168.50], EntityCreeper['Creeper'/394, l='MpServer', x=-469.50, y=67.00, z=193.50], EntityHorse['Horse'/395, l='MpServer', x=-459.16, y=69.00, z=184.83], EntitySkeleton['Skeleton'/398, l='MpServer', x=-443.30, y=69.00, z=189.76], EntityHorse['Horse'/399, l='MpServer', x=-454.85, y=67.00, z=200.96], EntitySheep['Sheep'/400, l='MpServer', x=-455.48, y=67.00, z=198.26], EntitySheep['Sheep'/401, l='MpServer', x=-450.49, y=68.00, z=197.81], EntitySkeleton['Skeleton'/403, l='MpServer', x=-429.34, y=68.00, z=169.79], EntityZombie['Zombie'/408, l='MpServer', x=-422.50, y=37.00, z=183.50], EntityHorse['Horse'/409, l='MpServer', x=-435.06, y=68.00, z=202.96], EntityHorse['Horse'/410, l='MpServer', x=-440.13, y=67.00, z=198.05], EntityZombie['Zombie'/411, l='MpServer', x=-443.50, y=68.00, z=192.50], EntityZombie['Zombie'/413, l='MpServer', x=-509.50, y=70.00, z=238.50], EntitySheep['Sheep'/436, l='MpServer', x=-422.19, y=68.00, z=206.17], EntitySheep['Sheep'/437, l='MpServer', x=-420.23, y=68.00, z=205.25], EntitySheep['Sheep'/439, l='MpServer', x=-392.18, y=64.00, z=178.66], EntitySheep['Sheep'/442, l='MpServer', x=-406.30, y=67.00, z=203.69], EntityPig['Pig'/443, l='MpServer', x=-417.78, y=69.00, z=221.54], EntitySkeleton['Skeleton'/445, l='MpServer', x=-398.50, y=67.00, z=218.50], EntitySkeleton['Skeleton'/446, l='MpServer', x=-394.70, y=66.00, z=220.39], EntityCreeper['Creeper'/447, l='MpServer', x=-426.50, y=34.00, z=254.50], EntitySkeleton['Skeleton'/448, l='MpServer', x=-421.50, y=68.00, z=250.73], EntitySheep['Sheep'/449, l='MpServer', x=-395.60, y=68.00, z=232.76], EntitySheep['Sheep'/452, l='MpServer', x=-396.45, y=68.00, z=230.77], EntityPig['Pig'/453, l='MpServer', x=-412.58, y=69.00, z=243.22], EntitySpider['Spider'/454, l='MpServer', x=-409.50, y=34.00, z=260.50], EntitySkeleton['Skeleton'/455, l='MpServer', x=-418.49, y=32.00, z=282.33], EntityBat['Bat'/456, l='MpServer', x=-423.63, y=24.96, z=295.14], EntityBat['Bat'/464, l='MpServer', x=-423.35, y=38.14, z=304.03], EntityCreeper['Creeper'/465, l='MpServer', x=-402.50, y=23.00, z=302.50], EntityBat['Bat'/466, l='MpServer', x=-416.25, y=32.10, z=299.25], EntityZombie['Zombie'/467, l='MpServer', x=-403.50, y=38.00, z=298.50], EntityBat['Bat'/468, l='MpServer', x=-401.48, y=60.10, z=295.83], EntityCyclops['Cyclops'/724, l='MpServer', x=-419.50, y=68.00, z=189.50], EntityZombie['Zombie'/469, l='MpServer', x=-413.50, y=41.00, z=323.50], EntityCreeper['Creeper'/473, l='MpServer', x=-408.50, y=15.00, z=313.50], EntitySkeleton['Skeleton'/474, l='MpServer', x=-405.50, y=25.00, z=316.50], EntitySkeleton['Skeleton'/475, l='MpServer', x=-408.20, y=53.00, z=306.66], EntityZombie['Zombie'/476, l='MpServer', x=-406.79, y=65.00, z=319.29], EntityCreeper['Creeper'/477, l='MpServer', x=-400.50, y=64.00, z=307.50], EntityCreeper['Creeper'/479, l='MpServer', x=-391.36, y=44.00, z=326.08], EntityCreeper['Creeper'/483, l='MpServer', x=-393.48, y=64.00, z=296.82], EntityPig['Pig'/230, l='MpServer', x=-523.46, y=85.00, z=303.73], EntityCreeper['Creeper'/231, l='MpServer', x=-522.50, y=80.00, z=295.50], EntityZombie['Zombie'/232, l='MpServer', x=-521.50, y=80.00, z=295.50], EntityWitch['Witch'/233, l='MpServer', x=-529.50, y=83.00, z=319.50], EntityPlayerSP['Asstuba'/100, l='MpServer', x=-470.72, y=72.49, z=250.73], EntitySkeleton['Skeleton'/505, l='MpServer', x=-547.50, y=27.00, z=235.50], EntityCreeper['Creeper'/507, l='MpServer', x=-501.50, y=70.00, z=301.50], EntityCreeper['Creeper'/509, l='MpServer', x=-479.18, y=67.00, z=284.58]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1883)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Asstuba'/100, l='MpServer', x=-470.72, y=72.49, z=250.73]]
	Chunk stats: MultiplayerChunkCache: 1089, 1089
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-112,64,240), Chunk: (at 0,4,0 in -7,15; contains blocks -112,0,240 to -97,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 28497 game time, 15124 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 99 total; [EntityBat['Bat'/518, l='MpServer', x=-472.25, y=27.10, z=172.48], EntitySheep['Sheep'/285, l='MpServer', x=-542.62, y=67.00, z=201.54], EntitySheep['Sheep'/286, l='MpServer', x=-543.61, y=67.00, z=204.47], EntityBat['Bat'/542, l='MpServer', x=-444.56, y=40.39, z=322.21], EntitySheep['Sheep'/287, l='MpServer', x=-543.59, y=67.00, z=201.65], EntityCreeper['Creeper'/289, l='MpServer', x=-535.50, y=68.00, z=188.50], EntitySkeleton['Skeleton'/290, l='MpServer', x=-499.50, y=54.00, z=188.50], EntityBat['Bat'/291, l='MpServer', x=-503.42, y=54.12, z=195.42], EntityBat['Bat'/292, l='MpServer', x=-514.34, y=24.03, z=185.13], EntityZombie['Zombie'/293, l='MpServer', x=-526.54, y=22.00, z=218.75], EntityBat['Bat'/294, l='MpServer', x=-488.49, y=43.93, z=168.61], EntitySkeleton['Skeleton'/295, l='MpServer', x=-486.50, y=64.00, z=180.50], EntitySkeleton['Skeleton'/296, l='MpServer', x=-498.50, y=35.00, z=195.50], EntitySheep['Sheep'/299, l='MpServer', x=-488.28, y=63.00, z=195.51], EntitySheep['Sheep'/300, l='MpServer', x=-486.30, y=63.00, z=194.44], EntityBat['Bat'/301, l='MpServer', x=-511.44, y=45.31, z=205.20], EntityPig['Pig'/302, l='MpServer', x=-513.71, y=73.00, z=237.54], EntitySpider['Spider'/305, l='MpServer', x=-489.50, y=66.00, z=210.50], EntitySheep['Sheep'/308, l='MpServer', x=-498.49, y=69.00, z=239.70], EntityPig['Pig'/309, l='MpServer', x=-519.47, y=70.00, z=254.72], EntityPig['Pig'/310, l='MpServer', x=-508.74, y=71.00, z=248.25], EntityPig['Pig'/311, l='MpServer', x=-513.49, y=72.00, z=260.25], EntitySheep['Sheep'/314, l='MpServer', x=-493.95, y=69.00, z=239.52], EntitySheep['Sheep'/315, l='MpServer', x=-488.55, y=67.16, z=241.46], EntitySheep['Sheep'/316, l='MpServer', x=-497.27, y=68.00, z=236.49], EntitySheep['Sheep'/317, l='MpServer', x=-524.51, y=67.06, z=280.97], EntitySkeleton['Skeleton'/321, l='MpServer', x=-542.50, y=69.00, z=263.50], EntityZombie['Zombie'/336, l='MpServer', x=-453.27, y=71.00, z=230.69], EntitySheep['Sheep'/341, l='MpServer', x=-469.33, y=69.00, z=258.73], EntitySheep['Sheep'/342, l='MpServer', x=-466.53, y=69.00, z=257.26], EntityZombie['Zombie'/345, l='MpServer', x=-481.79, y=65.00, z=288.53], EntityCreeper['Creeper'/346, l='MpServer', x=-463.80, y=66.00, z=281.60], EntityZombie['Zombie'/347, l='MpServer', x=-437.74, y=59.00, z=252.53], EntityPig['Pig'/350, l='MpServer', x=-433.30, y=71.00, z=247.23], EntitySheep['Sheep'/351, l='MpServer', x=-433.36, y=71.00, z=243.72], EntityPig['Pig'/352, l='MpServer', x=-504.80, y=72.00, z=305.76], EntityPig['Pig'/353, l='MpServer', x=-511.50, y=74.00, z=311.50], EntityPig['Pig'/354, l='MpServer', x=-503.74, y=71.00, z=312.48], EntitySpider['Spider'/103, l='MpServer', x=-475.00, y=68.00, z=227.00], EntitySheep['Sheep'/104, l='MpServer', x=-481.17, y=69.00, z=242.15], EntitySheep['Sheep'/361, l='MpServer', x=-462.68, y=66.00, z=280.44], EntitySheep['Sheep'/362, l='MpServer', x=-462.50, y=66.00, z=283.79], EntitySheep['Sheep'/363, l='MpServer', x=-460.16, y=66.00, z=281.21], EntitySheep['Sheep'/364, l='MpServer', x=-460.72, y=66.00, z=282.22], EntityCreeper['Creeper'/365, l='MpServer', x=-438.82, y=59.00, z=260.22], EntitySpider['Spider'/366, l='MpServer', x=-443.30, y=61.00, z=261.70], EntityPig['Pig'/367, l='MpServer', x=-435.47, y=65.00, z=276.75], EntitySpider['Spider'/379, l='MpServer', x=-437.50, y=38.00, z=308.50], EntityCreeper['Creeper'/380, l='MpServer', x=-441.50, y=64.00, z=315.50], EntityZombie['Zombie'/390, l='MpServer', x=-456.50, y=42.00, z=168.50], EntityCreeper['Creeper'/394, l='MpServer', x=-469.50, y=67.00, z=193.50], EntityHorse['Horse'/395, l='MpServer', x=-459.16, y=69.00, z=184.83], EntitySkeleton['Skeleton'/398, l='MpServer', x=-443.30, y=69.00, z=189.76], EntityHorse['Horse'/399, l='MpServer', x=-454.85, y=67.00, z=200.96], EntitySheep['Sheep'/400, l='MpServer', x=-455.48, y=67.00, z=198.26], EntitySheep['Sheep'/401, l='MpServer', x=-450.49, y=68.00, z=197.81], EntitySkeleton['Skeleton'/403, l='MpServer', x=-429.34, y=68.00, z=169.79], EntityZombie['Zombie'/408, l='MpServer', x=-422.50, y=37.00, z=183.50], EntityHorse['Horse'/409, l='MpServer', x=-435.06, y=68.00, z=202.96], EntityHorse['Horse'/410, l='MpServer', x=-440.13, y=67.00, z=198.05], EntityZombie['Zombie'/411, l='MpServer', x=-443.50, y=68.00, z=192.50], EntityZombie['Zombie'/413, l='MpServer', x=-509.50, y=70.00, z=238.50], EntitySheep['Sheep'/436, l='MpServer', x=-422.19, y=68.00, z=206.17], EntitySheep['Sheep'/437, l='MpServer', x=-420.23, y=68.00, z=205.25], EntitySheep['Sheep'/439, l='MpServer', x=-392.18, y=64.00, z=178.66], EntitySheep['Sheep'/442, l='MpServer', x=-406.30, y=67.00, z=203.69], EntityPig['Pig'/443, l='MpServer', x=-417.78, y=69.00, z=221.54], EntitySkeleton['Skeleton'/445, l='MpServer', x=-398.50, y=67.00, z=218.50], EntitySkeleton['Skeleton'/446, l='MpServer', x=-394.70, y=66.00, z=220.39], EntityCreeper['Creeper'/447, l='MpServer', x=-426.50, y=34.00, z=254.50], EntitySkeleton['Skeleton'/448, l='MpServer', x=-421.50, y=68.00, z=250.73], EntitySheep['Sheep'/449, l='MpServer', x=-395.60, y=68.00, z=232.76], EntitySheep['Sheep'/452, l='MpServer', x=-396.45, y=68.00, z=230.77], EntityPig['Pig'/453, l='MpServer', x=-412.58, y=69.00, z=243.22], EntitySpider['Spider'/454, l='MpServer', x=-409.50, y=34.00, z=260.50], EntitySkeleton['Skeleton'/455, l='MpServer', x=-418.49, y=32.00, z=282.33], EntityBat['Bat'/456, l='MpServer', x=-423.63, y=24.96, z=295.14], EntityBat['Bat'/464, l='MpServer', x=-423.35, y=38.14, z=304.03], EntityCreeper['Creeper'/465, l='MpServer', x=-402.50, y=23.00, z=302.50], EntityBat['Bat'/466, l='MpServer', x=-416.25, y=32.10, z=299.25], EntityZombie['Zombie'/467, l='MpServer', x=-403.50, y=38.00, z=298.50], EntityBat['Bat'/468, l='MpServer', x=-401.48, y=60.10, z=295.83], EntityCyclops['Cyclops'/724, l='MpServer', x=-419.50, y=68.00, z=189.50], EntityZombie['Zombie'/469, l='MpServer', x=-413.50, y=41.00, z=323.50], EntityCreeper['Creeper'/473, l='MpServer', x=-408.50, y=15.00, z=313.50], EntitySkeleton['Skeleton'/474, l='MpServer', x=-405.50, y=25.00, z=316.50], EntitySkeleton['Skeleton'/475, l='MpServer', x=-408.20, y=53.00, z=306.66], EntityZombie['Zombie'/476, l='MpServer', x=-406.79, y=65.00, z=319.29], EntityCreeper['Creeper'/477, l='MpServer', x=-400.50, y=64.00, z=307.50], EntityCreeper['Creeper'/479, l='MpServer', x=-391.36, y=44.00, z=326.08], EntityCreeper['Creeper'/483, l='MpServer', x=-393.48, y=64.00, z=296.82], EntityPig['Pig'/230, l='MpServer', x=-523.46, y=85.00, z=303.73], EntityCreeper['Creeper'/231, l='MpServer', x=-522.50, y=80.00, z=295.50], EntityZombie['Zombie'/232, l='MpServer', x=-521.50, y=80.00, z=295.50], EntityWitch['Witch'/233, l='MpServer', x=-529.50, y=83.00, z=319.50], EntityPlayerSP['Asstuba'/100, l='MpServer', x=-470.72, y=72.49, z=250.73], EntitySkeleton['Skeleton'/505, l='MpServer', x=-547.50, y=27.00, z=235.50], EntityCreeper['Creeper'/507, l='MpServer', x=-501.50, y=70.00, z=301.50], EntityCreeper['Creeper'/509, l='MpServer', x=-479.18, y=67.00, z=284.58]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1162207472 bytes (1108 MB) / 3422552064 bytes (3264 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:SoftRefLRUPolicyMSPerMB=1
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID         | Version      | Source                        | Signature                                |
	|:------ |:---------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft  | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp        | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge      | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | llibrary   | 1.7.19       | llibrary-1.7.19-1.12.2.jar    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire | 1.8.0        | iceandfire-1.8.0.jar          | None                                     |
	| LCHIJA | incontrol  | 3.9.15       | incontrol-1.12-3.9.15.jar     | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 431.60' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: forge-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.60, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 28x Intel(R) Xeon(R) CPU E5-2697v3 @ 2.59GHz
```

**Comment by McJty** [comment]
Ok, that's a bug on my side. I'll have to fix that. It's an easy fix. I can do that later today

**Comment by McJty** [comment]
3.9.16 fixes this bug

**Comment by Asstuba** [comment]
Awesome that you fixed the exception, but this still lets them through:

```
[
    {
        "dimension": 0,
        "mob": [
            "iceandfire:cyclops"
        ],
        "biome": [
            "Plains"
        ],
        "maxcount": {
            "perchunk": true,
            "amount": 3
        },
        "block": "minecraft:grass",
        "seesky": true,
        "isnotcolliding": true,
        "onjoin": true,
        "result": "allow"
    },
    {
        "dimension": 0,
        "mob": [
            "iceandfire:cyclops"
        ],
        "onjoin": true,
        "result": "deny"
    }
]
```
