### ISSUE TITLE
This mod causes crash

### ISSUE THREAD

**Issue by efficient-efi** [McJty/InControl#361]
---- Minecraft Crash Report ----
// Don't do that.

Time: 22/11/21 16:44
Description: Exception generating new chunk

java.lang.ClassCastException: net.minecraft.world.gen.WorldGenRegion cannot be cast to net.minecraft.world.server.ServerWorld
	at mcjty.tools.rules.CommonRuleEvaluator.lambda$addMaxSpawnDistCheck$34(CommonRuleEvaluator.java:676) ~[?:1.16-5.1.1] {re:classloading}
	at mcjty.tools.rules.CommonRuleEvaluator$$Lambda$4743/280142111.apply(Unknown Source) ~[?:?] {}
	at mcjty.incontrol.rules.support.GenericRuleEvaluator.match(GenericRuleEvaluator.java:595) ~[?:1.16-5.1.1] {re:classloading}
	at mcjty.incontrol.rules.SpawnRule.match(SpawnRule.java:257) ~[?:1.16-5.1.1] {re:classloading}
	at mcjty.incontrol.ForgeEventHandlers.onEntitySpawnEvent(ForgeEventHandlers.java:104) ~[?:1.16-5.1.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_87_ForgeEventHandlers_onEntitySpawnEvent_CheckSpawn.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3359/938715230.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.canEntitySpawn(ForgeHooks.java:1166) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:366) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.NoiseChunkGenerator.func_230354_a_(NoiseChunkGenerator.java:623) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus.func_222602_b(ChunkStatus.java:89) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2340/1481739002.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:240) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$6598/908250691.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading,re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$6595/1956092736.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$6545/410317338.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mcjty.tools.rules.CommonRuleEvaluator.lambda$addMaxSpawnDistCheck$34(CommonRuleEvaluator.java:676) ~[?:1.16-5.1.1] {re:classloading}
	at mcjty.tools.rules.CommonRuleEvaluator$$Lambda$4743/280142111.apply(Unknown Source) ~[?:?] {}
	at mcjty.incontrol.rules.support.GenericRuleEvaluator.match(GenericRuleEvaluator.java:595) ~[?:1.16-5.1.1] {re:classloading}
	at mcjty.incontrol.rules.SpawnRule.match(SpawnRule.java:257) ~[?:1.16-5.1.1] {re:classloading}
	at mcjty.incontrol.ForgeEventHandlers.onEntitySpawnEvent(ForgeEventHandlers.java:104) ~[?:1.16-5.1.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_87_ForgeEventHandlers_onEntitySpawnEvent_CheckSpawn.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3359/938715230.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.canEntitySpawn(ForgeHooks.java:1166) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:366) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.NoiseChunkGenerator.func_230354_a_(NoiseChunkGenerator.java:623) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus.func_222602_b(ChunkStatus.java:89) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2340/1481739002.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:240) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Chunk to be generated --
Details:
	Location: 25,33
	Position hash: 141733920793
	Generator: com.legacy.blue_skies.world.SkiesNoiseChunkGenerator@51ace575
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$6598/908250691.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$6595/1956092736.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$6545/410317338.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['efficient_efi'/81, l='ServerLevel[新規ワールド]', x=-0.10, y=91.25, z=18.56]]
	Chunk stats: ServerChunkCache: 7530
	Level dimension: blue_skies:everbright
	Derived: true
	Level spawn location: World: (54,63,139), Chunk: (at 6,3,11 in 3,8; contains blocks 48,0,128 to 63,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2156 game time, 2156 day time
	Level name: 新規ワールド
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$6406/381872803.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 14105064088 bytes (13451 MB) / 17012097024 bytes (16224 MB) up to 25769803776 bytes (24576 MB)
	CPUs: 20
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx24G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		incontrol-1.16-5.1.1.jar                          |InControl                     |incontrol                     |1.16-5.1.1          |DONE      |Manifest: NOSIGNATURE
		blue_skies-1.16.5-1.1.3.jar                       |Blue Skies                    |blue_skies                    |1.1.3               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		rubidium-0.2.10.jar                               |Rubidium                      |rubidium                      |0.2.10              |DONE      |Manifest: NOSIGNATURE
		oculus-1.2.6.jar                                  |Oculus                        |oculus                        |1.2.6               |DONE      |Manifest: NOSIGNATURE
		initialSpawnDimension-1.16.5-1.0.2.jar            |Initial Spawn Dimension       |isd                           |1.16.5-1.0.2        |DONE      |Manifest: NOSIGNATURE
		OpenLoader-1.16.5-9.0.3.jar                       |OpenLoader                    |openloader                    |9.0.3               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		structure_gel-1.16.5-1.7.8.jar                    |Structure Gel API             |structure_gel                 |1.7.8               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.152.jar                          |Just Enough Items             |jei                           |7.7.1.152           |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: f3a45001-22e4-4691-b155-c59b3fc5b013
	Loaded Shaderpack: Sildur's+Vibrant+Shaders+v1.41+Extreme-VL.zip
		Profile: Custom (+15 options changed by user)
	Player Count: 1 / 8; [ServerPlayerEntity['efficient_efi'/81, l='ServerLevel[新規ワールド]', x=-0.10, y=91.25, z=18.56]]
	Data Packs: vanilla, mod:blue_skies (incompatible), mod:jei, mod:rubidium (incompatible), mod:oculus, mod:forge, mod:isd (incompatible), mod:openloader, mod:structure_gel, mod:incontrol (incompatible), openloader/data/efi's_recipes
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

---------------------------------------------------------------------------------------------------------------------------------------------------
spawner.json

[
  {
    "mob":"blue_skies:nyctofly",
    "persecond": 0.5,
    "attempts": 5,
    "amount": {
      "minimum": 1,
      "maximum": 2
    },
    "conditions": {
      "dimension": "blue_skies:everbright",
      "maxhostile": 30
    }
  },
  {
    "mob":"blue_skies:emberback",
    "persecond": 0.5,
    "attempts": 5,
    "amount": {
      "minimum": 1,
      "maximum": 2
    },
    "conditions": {
      "dimension": "blue_skies:everbright",
      "maxhostile": 30
    }
  },
  {
    "mob":"blue_skies:infested_swarmer",
    "persecond": 0.5,
    "attempts": 20,
    "amount": {
      "minimum": 2,
      "maximum": 5
    },
    "conditions": {
      "dimension": "blue_skies:everbright",
      "maxhostile": 30,
	  "maxthis":16
    }
  }
]

---------------------------------------------------------------------------------------------------------------------------------------------------
spawn.json

[
{
	"maxspawndist":24,
	"result":"deny"
}
]

**Comment by efficient-efi** [comment]
ok it's solved.
