### ISSUE TITLE
Minimum vertical distance must be smaller than maximum

### ISSUE THREAD

**Issue by leezallen** [McJty/InControl#377]
Since updating the mod I am now receiving the following error (which I assume is from the recent enhancement)

[13:13:29] [Worker-Main-14/ERROR]: JSON error in 'spawner.json': check log for details (Minimum vertical distance must be smaller then maximum!)
[13:13:29] [Worker-Main-14/ERROR]: Error parsing 'spawner.json'
java.lang.IllegalStateException: Minimum vertical distance must be smaller then maximum!
	at mcjty.incontrol.spawner.SpawnerConditions.validate(SpawnerConditions.java:121) ~[incontrol-1.18-6.1.7.jar%2376!/:1.18-6.1.7]
	at mcjty.incontrol.spawner.SpawnerRule.parse(SpawnerRule.java:210) ~[incontrol-1.18-6.1.7.jar%2376!/:1.18-6.1.7]
	at mcjty.incontrol.spawner.SpawnerParser.readRules(SpawnerParser.java:23) ~[incontrol-1.18-6.1.7.jar%2376!/:1.18-6.1.7]
	at mcjty.incontrol.setup.ModSetup.init(ModSetup.java:36) ~[incontrol-1.18-6.1.7.jar%2376!/:1.18-6.1.7]
	at mcjty.incontrol.InControl.lambda$new$0(InControl.java:20) ~[incontrol-1.18-6.1.7.jar%2376!/:1.18-6.1.7]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.2.jar%23103!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.2.2.jar%23102!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

But my spawner.json does not reference minverticaldist or maxverticaldist anywhere. Example entry would be... all of them are very similar!

   {
        "phase": "after_day3",
        "mob": "minecraft:zombie",
        "persecond": 0.5,
        "attempts": 5,
        "amount": {
            "minimum": 1,
            "maximum": 5
        },
        "conditions": {
            "dimension": "minecraft:overworld",
            "norestrictions": false,
            "mindist": 28,
            "maxdist": 80,
            "maxthis": 20
        }

Do I manually need to set a minverticaldist/maxverticaldist? Are there default values?

**Comment by leezallen** [comment]
Should have mentioned I am using 1.18.2 version 6.1.7

**Comment by McJty** [comment]
Should be fixed now

**Comment by leezallen** [comment]
Tested and confirmed as working. Thank you for the quick response!
