### ISSUE TITLE
Error on first startup: invalid plugin.yml

### ISSUE THREAD

**Issue by Grumblesaur** [McJty/InControl#46]
```
[20:40:52 ERROR]: Could not load 'plugins/incontrol-1.12-3.6.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-325fbc7-dc7d31b]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.12.2.jar:git-Spigot-325fbc7-dc7d31b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2.jar:git-Spigot-325fbc7-dc7d31b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-325fbc7-dc7d31b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-325fbc7-dc7d31b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more

```

My spigot server complains that `incontrol-3.6.0.jar` does not contain `plugin.yml`. I've checked several other versions (including the newest) and none of them seem to have this file. They all fail to load in a similar way.

If there is a certain installation step I'm missing beyond dropping it into the `plugins` folder, it would be nice to see that in some documentation.

**Comment by McJty** [comment]
In Control is not a plugin. It is a mod. Place it in the mods folder

**Comment by Grumblesaur** [comment]
Well, shut my mouth. Sorry to bother you.
