### ISSUE TITLE
No Enum constant for category

### ISSUE THREAD

**Issue by JustCharl** [McJty/InControl#465]
**Version: 1.21.1-10.0.2**
**Minecraft Version: Neoforge - 21.1.80**
^ This has also happened on earlier and later versions of Neoforge and the mod.

---

I wanted to make the max hostile mob and creature spawn rates to be increased (to increase difficulty at night and to make the days feel more fuller), however, when copying the code from the wiki and slightly tweaking, when in-game, it's stating the below:

```
JSON error in 'spawner.json': check log for details (No enum constant net.minecraft.world.entity.MobCategory.monster)
```
```
JSON error in 'spawner.json': check log for details (No enum constant net.minecraft.world.entity.MobCategory.creature)
```

---
The below is the InControl spawner.json file, which when input into the validator, states "success".

```
[
    {
      "mobsfrombiome": "monster",
      "persecond": 0.5,
      "attempts": 20,
      "amount": {
        "minimum": 2,
        "maximum": 5
      },
      "conditions": {
        "dimension": "minecraft:overworld",
        "maxhostile": 200
      }
    },

    {
      "mobsfrombiome": "creature",
      "persecond": 0.5,
      "attempts": 20,
      "amount": {
        "minimum": 2,
        "maximum": 5
      },
      "conditions": {
        "dimension": "minecraft:overworld",
        "maxpeaceful": 125
      }
    }
  ]
```

---
The full relative section of the log for the hostile mob section, for example, is below:
```
[04Dec2024 15:26:16.029] [Server thread/ERROR] [incontrol/]: JSON error in 'spawner.json': check log for details (No enum constant net.minecraft.world.entity.MobCategory.monster)
[04Dec2024 15:26:16.029] [Server thread/ERROR] [incontrol/]: Error parsing 'spawner.json'
java.lang.IllegalArgumentException: No enum constant net.minecraft.world.entity.MobCategory.monster
	at java.base/java.lang.Enum.valueOf(Unknown Source) ~[?:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.MobCategory.valueOf(MobCategory.java:6) ~[client-1.21.1-20240808.144430-srg.jar%23699!/:?]
	at TRANSFORMER/incontrol@1.21-10.0.2/mcjty.incontrol.spawner.SpawnerRule.parse(SpawnerRule.java:172) ~[incontrol-1.21-10.0.2.jar%23934!/:1.21-10.0.2]
	at TRANSFORMER/incontrol@1.21-10.0.2/mcjty.incontrol.spawner.SpawnerParser.readRules(SpawnerParser.java:23) ~[incontrol-1.21-10.0.2.jar%23934!/:1.21-10.0.2]
	at TRANSFORMER/incontrol@1.21-10.0.2/mcjty.incontrol.spawner.SpawnerSystem.reloadRules(SpawnerSystem.java:49) ~[incontrol-1.21-10.0.2.jar%23934!/:1.21-10.0.2]
	at TRANSFORMER/incontrol@1.21-10.0.2/mcjty.incontrol.ForgeEventHandlers.tryLoadRules(ForgeEventHandlers.java:58) ~[incontrol-1.21-10.0.2.jar%23934!/:1.21-10.0.2]
	at TRANSFORMER/incontrol@1.21-10.0.2/mcjty.incontrol.ForgeEventHandlers.onLevelLoad(ForgeEventHandlers.java:50) ~[incontrol-1.21-10.0.2.jar%23934!/:1.21-10.0.2]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%23109!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%23109!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.createLevels(MinecraftServer.java:375) ~[client-1.21.1-20240808.144430-srg.jar%23699!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:337) ~[client-1.21.1-20240808.144430-srg.jar%23699!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.initServer(IntegratedServer.java:77) ~[client-1.21.1-20240808.144430-srg.jar%23699!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:670) ~[client-1.21.1-20240808.144430-srg.jar%23699!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23699!/:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by McJty** [comment]
Try capitalizing it: "MONSTER"

**Comment by JustCharl** [comment]
I've just done what you suggested, capitalizing "monster" to "MONSTER" and the same with creature, and both don't fix anything. 
![image](https://github.com/user-attachments/assets/c8f35293-66b4-4dcb-af04-5cb32fcd07de)
![image](https://github.com/user-attachments/assets/896e9021-8f63-4016-89f1-1be2af7e91ab)

**Comment by Neev4n** [comment]
i'm also having the same issue with neoforge 1.21.1, do you find a fix?

**Comment by McJty** [comment]
Before I can find a fix I need to find time first

**Comment by ostiwe** [comment]
Same issue, neoforge 1.21.1


```
[13:32:25] [Server thread/ERROR] [incontrol/]: JSON error in 'spawner.json': check log for details (No enum constant net.minecraft.world.entity.MobCategory.monster)
[13:32:25] [Server thread/ERROR] [incontrol/]: Error parsing 'spawner.json'
java.lang.IllegalArgumentException: No enum constant net.minecraft.world.entity.MobCategory.monster
	at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?] {re:mixin}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.MobCategory.valueOf(MobCategory.java:6) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:classloading}
	at TRANSFORMER/incontrol@1.21-10.1.3/mcjty.incontrol.spawner.SpawnerRule.parse(SpawnerRule.java:172) ~[incontrol-1.21-10.1.3.jar%23171!/:1.21-10.1.3] {re:classloading}
	at TRANSFORMER/incontrol@1.21-10.1.3/mcjty.incontrol.spawner.SpawnerParser.readRules(SpawnerParser.java:23) ~[incontrol-1.21-10.1.3.jar%23171!/:1.21-10.1.3] {re:classloading}
	at TRANSFORMER/incontrol@1.21-10.1.3/mcjty.incontrol.spawner.SpawnerSystem.reloadRules(SpawnerSystem.java:49) ~[incontrol-1.21-10.1.3.jar%23171!/:1.21-10.1.3] {re:classloading}
	at TRANSFORMER/incontrol@1.21-10.1.3/mcjty.incontrol.commands.CmdReload.run(CmdReload.java:38) ~[incontrol-1.21-10.1.3.jar%23171!/:1.21-10.1.3] {re:classloading}
	at MC-BOOTSTRAP/brigadier@1.3.10/com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar%2399!/:?] {}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:29) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:8) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:107) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.Commands.executeCommandInContext(Commands.java:363) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.Commands.performCommand(Commands.java:284) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:1282) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$7(ServerGamePacketListenerImpl.java:1269) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:mixin,re:computing_frames,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:872) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ponder-common.mixins.json:accessor.MinecraftServerAccessor from mod ponder,pl:mixin:APP:xaerohud.mixins.json:MixinMinecraftServer from mod xaerominimap,pl:mixin:APP:xaeroworldmap.mixins.json:MixinMinecraftServer from mod xaeroworldmap,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:170) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ponder-common.mixins.json:accessor.MinecraftServerAccessor from mod ponder,pl:mixin:APP:xaerohud.mixins.json:MixinMinecraftServer from mod xaerominimap,pl:mixin:APP:xaeroworldmap.mixins.json:MixinMinecraftServer from mod xaeroworldmap,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:855) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ponder-common.mixins.json:accessor.MinecraftServerAccessor from mod ponder,pl:mixin:APP:xaerohud.mixins.json:MixinMinecraftServer from mod xaerominimap,pl:mixin:APP:xaeroworldmap.mixins.json:MixinMinecraftServer from mod xaeroworldmap,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:849) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ponder-common.mixins.json:accessor.MinecraftServerAccessor from mod ponder,pl:mixin:APP:xaerohud.mixins.json:MixinMinecraftServer from mod xaerominimap,pl:mixin:APP:xaeroworldmap.mixins.json:MixinMinecraftServer from mod xaeroworldmap,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:821) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ponder-common.mixins.json:accessor.MinecraftServerAccessor from mod ponder,pl:mixin:APP:xaerohud.mixins.json:MixinMinecraftServer from mod xaerominimap,pl:mixin:APP:xaeroworldmap.mixins.json:MixinMinecraftServer from mod xaeroworldmap,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:826) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ponder-common.mixins.json:accessor.MinecraftServerAccessor from mod ponder,pl:mixin:APP:xaerohud.mixins.json:MixinMinecraftServer from mod xaerominimap,pl:mixin:APP:xaeroworldmap.mixins.json:MixinMinecraftServer from mod xaeroworldmap,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:712) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ponder-common.mixins.json:accessor.MinecraftServerAccessor from mod ponder,pl:mixin:APP:xaerohud.mixins.json:MixinMinecraftServer from mod xaerominimap,pl:mixin:APP:xaeroworldmap.mixins.json:MixinMinecraftServer from mod xaeroworldmap,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23150!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ponder-common.mixins.json:accessor.MinecraftServerAccessor from mod ponder,pl:mixin:APP:xaerohud.mixins.json:MixinMinecraftServer from mod xaerominimap,pl:mixin:APP:xaeroworldmap.mixins.json:MixinMinecraftServer from mod xaeroworldmap,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {}
```

**Comment by McJty** [comment]
Sorry for the slow response. First I had no time but then I lost track of this bug. Should be fixed now in 10.1.4
