### ISSUE TITLE
Couldn't process command: ctrlloadspawn

### ISSUE THREAD

**Issue by HurtsAsHell** [McJty/InControl#97]
## Spawn.json
```
[
  {
    "mob": "Zombie",
    "result": "default",
    "nbt": {
      "Attributes": [
        {
          "Base": 40.0,
          "Name": "generic.maxHealth"
        },
        {
          "Base": 0.23,
          "Modifiers": [
            {
              "Operation": 2,
              "Amount": -0.5,
              "Name": "effect.moveSlowdown 0"
            }
          ],
          "Name": "generic.movementSpeed"
        }
      ]
    }
  }
]
```

**Copied from your wiki**

## Console 
```
Couldn't process command: ctrlloadspawn
java.lang.ArrayIndexOutOfBoundsException: 0
	at mcjty.incontrol.CmdLoadSpawn.func_184881_a(CmdLoadSpawn.java:24)
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939)
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
```

I used the `/ctrlloadspawn` command

_Do I need to add anything else to the json?_

**Comment by HurtsAsHell** [comment]
I would just like to increase the max life of all the mobs so technically I should do this : 
### This is an Example
```
[
  {
    "mob": ["Zombie","Creeper"],
    "result": "default",
    "nbt": {
      "Attributes": [
        {
          "Base": 40.0,
          "Name": "generic.maxHealth"
        }
      ]
    }
  }
]
```

**Is it correct?**

**Comment by McJty** [comment]
You need to add a parameter to /ctrlloadspawn (name of file to read). Like /ctrlloadspawn spawn.json

**Comment by HurtsAsHell** [comment]
okay, i has tested but I received that : 

```
15:02:45 | STDOUT | Server thread | info | [mcjty.incontrol.rules.RulesManager:readCustomSpawn:44]: file = spawn.json
-- | -- | -- | -- | --
15:02:45 | incontrol | Server thread | warn | Error reading file 'spawn.json'!
15:02:45 | net.minecraft.client.gui.GuiNewChat | Client thread | info | [CHAT] §cError reading file 'spawn.json'!

```

**Comment by HurtsAsHell** [comment]
I do not know if it can be useful but I am from 1.12.2

**Comment by McJty** [comment]
Just use the /ctrlreload command. That reloads all rules without extra parameter. That will be more useful

**Comment by HurtsAsHell** [comment]
But is this code correct?
```
[
  {
    "mob": ["Zombie","Creeper"],
    "result": "default",
    "nbt": {
      "Attributes": [
        {
          "Base": 40.0,
          "Name": "generic.maxHealth"
        }
      ]
    }
  }
]
```

**Comment by HurtsAsHell** [comment]
because even if I do reload the zombies are always 20 hp

**Comment by McJty** [comment]
That looks ok. Try /ctrldebug to see if that rule is actually being used

**Comment by HurtsAsHell** [comment]
enough that I look at the console after or do I have to go to a specific folder?

**Comment by HurtsAsHell** [comment]
```

15:52:33 | incontrol | Server thread | info | Rule 0: DEFAULT entity: Zombie y: 63.0 biome: Beach
-- | -- | -- | -- | --
15:52:35 | incontrol | Server thread | info | Rule 0: DEFAULT entity: Zombie y: 15.0 biome: Deep Ocean
15:52:35 | incontrol | Server thread | info | Rule 0: DEFAULT entity: Zombie y: 15.0 biome: Deep Ocean
15:53:31 | incontrol | Server thread | info | Rule 0: DEFAULT entity: Zombie y: 22.0 biome: Deep Ocean
15:53:31 | incontrol | Server thread | info | Rule 0: DEFAULT entity: Zombie y: 22.0 biome: Deep Ocean

```

is the rule active?

**Comment by McJty** [comment]
yes but it appears your nbt isn't working. Anyway why aren't you using the healthmultiply and healthadd actions instead?

**Comment by HurtsAsHell** [comment]
I was trying to follow your tutorial

**Comment by HurtsAsHell** [comment]
okay, i'm using the healtadd and now it work

**Comment by HurtsAsHell** [comment]
thanks
